//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentAccounting.Logic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("StudentAccounting.Logic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to testemail@mail.ru.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назначение наставником.
        /// </summary>
        internal static string Email_Mentor_Subject {
            get {
                return ResourceManager.GetString("Email_Mentor_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша заявка на практику одобренна, пожалуйста ожидайте дальнейшей информации на указанную почту или звонка на телефон..
        /// </summary>
        internal static string Email_Message_Body_Accept {
            get {
                return ResourceManager.GetString("Email_Message_Body_Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению ваша заявка была откланнена по причине отсутствия мест на данном направлении..
        /// </summary>
        internal static string Email_Message_Body_Refuse_NotEnoughSpace {
            get {
                return ResourceManager.GetString("Email_Message_Body_Refuse_NotEnoughSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to К сожалению ваша заявка была откланнена по причине несоотвествия вашей специальности выбранному направлению практики..
        /// </summary>
        internal static string Email_Message_Body_Refuse_WrongSpecialty {
            get {
                return ResourceManager.GetString("Email_Message_Body_Refuse_WrongSpecialty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша заявка была успешно оформлена. Ожидайте ответа на указанный вами номер телефона, либо почту..
        /// </summary>
        internal static string Email_Message_Body_Request {
            get {
                return ResourceManager.GetString("Email_Message_Body_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заявка на практику.
        /// </summary>
        internal static string Email_Message_Subject {
            get {
                return ResourceManager.GetString("Email_Message_Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test_smtp.
        /// </summary>
        internal static string SMTP {
            get {
                return ResourceManager.GetString("SMTP", resourceCulture);
            }
        }
    }
}
